### ISSUE TITLE
Derby DB Folder not recommendable 

### ISSUE THREAD

**Issue by krusk8** [entando/entando-archetypes#2]
It is not recommendable to place the default Derby DB folder into the Target folder. 
In development environment you have another DB configured, ok, but following the getting started wiki 

"mvn archetype:generate -Dfilter=entando-archetype-portal-bootstrap"
"mvn clean jetty:run"

You have excluded it in the pom file, ok, but deleting Target folder manually caused me to lose all my DB data.

<exclude>**/derby/production/**</exclude>

**Comment by MEM2677** [comment]
Hi! We introduced Derby as a means to have a portal running in seconds, usually for a standalone/demo or for a first contact with the platform. What you say is certainly true, and for this reason one of the first things I do when starting a new project is to switch to another DBMS or have data backed up from the admin console.
However we  appreciate your input and I'll have your request inserted in the 'desiderata' for the next release!

**Comment by eugeniosant** [comment]
If you look at https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html, it soon becomes clear that the "target" folder is the only place where we can put the derby folder; obviously we can not allow (by default) to store these files outside the maven project.
In any case, the pom.xml is configured to not delete the "derby" folder when you run the goal "clean".
However, it's possible to change the location of the folder by configuring the filter in use (located into folder src/main/filters).
Thanks for your input.
